package mdtnh.abilities;

import arc.Events;
import arc.math.Angles;
import arc.struct.IntSeq;
import arc.util.Time;
import mindustry.Vars;
import mindustry.content.Fx;
import mindustry.entities.Units;
import mindustry.entities.abilities.Ability;
import mindustry.game.EventType.UnitCreateEvent;
import mindustry.gen.Groups;
import mindustry.gen.Unit;
import mindustry.type.UnitType;

/**
 * Drone bay with per-owner counting.
 *
 * Each copied ability instance stores the IDs of the drones generated by that specific
 * carrier. Manually spawned drones, and drones created by other carriers, do not consume
 * this carrier's cap.
 *
 * Phase-1 limitation: this owner list is runtime state and is not serialized into a save.
 * A production MAX drone system should later persist ownership explicitly.
 */
public class DroneBayAbility extends MdtAbility {

    public UnitType droneType;
    public float spawnTime = 60f * 10f;
    public float spawnDistance = 16f;
    /** Legacy compatibility field. Per-owner counting no longer uses spatial range. */
    public float countRange = 260f;
    public int maxDrones = 3;

    protected float timer;
    protected IntSeq ownedDroneIds = new IntSeq();

    public DroneBayAbility(UnitType droneType) {
        super("dronebay");
        this.droneType = droneType;
    }

    @Override
    public DroneBayAbility copy() {
        DroneBayAbility copy = (DroneBayAbility)super.copy();
        copy.ownedDroneIds = new IntSeq();
        copy.timer = 0f;
        return copy;
    }

    @Override
    public void created(Unit unit) {
        ownedDroneIds.clear();
        timer = 0f;
    }

    @Override
    public void update(Unit unit) {
        if (droneType == null) return;

        pruneOwned(unit);

        if (ownedDroneIds.size >= maxDrones) {
            timer = Math.min(timer, spawnTime);
            return;
        }

        timer += Time.delta * Vars.state.rules.unitBuildSpeed(unit.team);
        if (timer < spawnTime) return;
        if (!Units.canCreate(unit.team, droneType)) return;

        float x = unit.x + Angles.trnsx(unit.rotation, spawnDistance);
        float y = unit.y + Angles.trnsy(unit.rotation, spawnDistance);

        Fx.spawn.at(x, y);

        Unit drone = droneType.create(unit.team);
        drone.set(x, y);
        drone.rotation = unit.rotation;

        Events.fire(new UnitCreateEvent(drone, null, unit));

        if (!Vars.net.client()) {
            drone.add();
            Units.notifyUnitSpawn(drone);
            ownedDroneIds.add(drone.id);
        }

        timer = 0f;
    }

    private void pruneOwned(Unit owner) {
        for (int i = ownedDroneIds.size - 1; i >= 0; i--) {
            Unit drone = Groups.unit.getByID(ownedDroneIds.get(i));

            if (drone == null
                    || !drone.isValid()
                    || drone.team != owner.team
                    || drone.type != droneType) {
                ownedDroneIds.removeIndex(i);
            }
        }
    }
}
